# Simulation Exercises

In [1]:
import numpy as np
import pandas as pd
np.random.seed(29)

### How likely is it that you roll doubles when rolling two dice?

In [2]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [2, 5],
       [1, 4],
       [4, 6]])

In [3]:
doubles = []
for roll in rolls:
    if roll[0] == roll[1]:
        doubles.append(1)
    else:
        doubles.append(0)

percent_doubles = sum(doubles)/len(doubles)
print(f"Based on a simulation of 10,000 rolls of two dice, the probability of rolling doubles is {percent_doubles}.")

Based on a simulation of 10,000 rolls of two dice, the probability of rolling doubles is 0.1709.


### If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [4]:
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = np.random.choice([0,1], n_trials * n_coins).reshape(nrows, ncols)
flips

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0]])

In [5]:
sums_by_trial = flips.sum(axis=1)
sums_by_trial

array([3, 5, 6, ..., 3, 6, 2])

In [6]:
exactly_3 = sums_by_trial == 3
exactly_3

array([ True, False, False, ...,  True, False, False])

In [7]:
exactly_3_rate = exactly_3.astype(int).mean()
print(f"Based on a simulation of 10,000 trials of 8 consecutive coin flips, the probability of flipping exactly three heads is {exactly_3_rate}.")

Based on a simulation of 10,000 trials of 8 consecutive coin flips, the probability of flipping exactly three heads is 0.2243.


### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [8]:
p_datasci = 0.25
n_boards = n_cols = 2
n_drives = n_rows = 10 ** 5

data = np.random.random((n_rows, n_cols))
data

array([[0.52367416, 0.30110826],
       [0.22483308, 0.89903466],
       [0.32563666, 0.01721882],
       ...,
       [0.46862724, 0.28377202],
       [0.62598687, 0.95912283],
       [0.44980969, 0.88367756]])

In [9]:
datasci_sighting = data < p_datasci
datasci_sighting

array([[False, False],
       [ True, False],
       [False,  True],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [10]:
datasci_sighting.sum(axis=1)

array([0, 1, 1, ..., 0, 0, 0])

In [11]:
(datasci_sighting.sum(axis=1) >= 2).mean()
print(f"Based on 10,000 simulated drives by two billboards, the probability of both billboards containing data science students is {(datasci_sighting.sum(axis=1) >= 2).mean()}.")

Based on 10,000 simulated drives by two billboards, the probability of both billboards containing data science students is 0.06325.


### Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [12]:
friday_stock = []
for num in range(10000):
    stock = 17
    for n in range(5):
        stock -= np.random.uniform(low=1.5, high=4.5)
    friday_stock.append(stock)

In [13]:
in_stock = []
for stock in friday_stock:
    if stock >= 1:
        in_stock.append(1)
    else:
        in_stock.append(0)

In [14]:
chance_for_tart = sum(in_stock)/len(in_stock)
print(f"Based on a simulation of 10,000 weeks, the chance that there is at least one pop tart remaining in stock after 5 days of purchases is {chance_for_tart}.")

Based on a simulation of 10,000 weeks, the chance that there is at least one pop tart remaining in stock after 5 days of purchases is 0.6979.


### Compare Heights

#### Men have an average height of 178 cm and standard deviation of 8cm.
#### Women have a mean of 170, sd = 6cm.
#### If a man and woman are chosen at random, P(woman taller than man)?

In [26]:
man_height = np.random.normal(178, 8, size=(10000,1)).tolist()
woman_height = np.random.normal(170,6, size=(10000,1)).tolist()

In [27]:
woman_taller = []
for i in range(len(man_height)):
    if woman_height[i][0] > man_height[i][0]:
        woman_taller.append(1)
    else:
        woman_taller.append(0)

In [30]:
chance_woman_taller = sum(woman_taller)/len(woman_taller)
print(f"After simulating 10,000 comparisons of a random woman to a random man, the probability that any given woman is taller than any given man is {chance_woman_taller}.")

After simulating 10,000 comparisons of a random woman to a random man, the probability that any given woman is taller than any given man is 0.2205.


### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

### How likely is it that 450 students all download anaconda without an issue?

### There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

### How likely is it that a food truck will show up sometime this week?

### If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?