# Simulation Exercises

In [1]:
import numpy as np
import pandas as pd
np.random.seed(29)

### How likely is it that you roll doubles when rolling two dice?

#### SOLUTION ONE

In [51]:
# This creates a numpy array of outcomes. 
# Each element in the array will be a pair of numbers representing the numbers rolled.
# The array will be 10,000 elements long, representing 10,000 trials of dice thrown
n_trials = nrows = 100000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[4, 5],
       [4, 6],
       [2, 1],
       ...,
       [1, 4],
       [5, 2],
       [4, 2]])

In [52]:
# The empty list 'doubles' will contain a boolean series of 0's and 1's
# This iterates through the numpy array and checks each pair
# If the pair is 
doubles = []
for roll in rolls:
    if roll[0] == roll[1]:
        doubles.append(1)
    else:
        doubles.append(0)

percent_doubles = sum(doubles)/len(doubles)
print(f"Based on a simulation of 100,000 rolls of two dice, the probability of rolling doubles is {percent_doubles}.")

Based on a simulation of 100,000 rolls of two dice, the probability of rolling doubles is 0.16648.


#### SOLUTION TWO

In [41]:
# Using DataFrames
rolls = pd.DataFrame()
rolls['die1'] = np.random.choice([1, 2, 3, 4, 5, 6], size=100000)
rolls['die2'] = np.random.choice([1, 2, 3, 4, 5, 6], size=100000)
rolls.head()

die1  die2
0     5     3
1     4     1
2     5     1
3     6     2
4     5     1

In [44]:
rolls['is_pair'] = rolls.die1 == rolls.die2
rolls.head()

die1  die2  is_pair
0     5     3    False
1     4     1    False
2     5     1    False
3     6     2    False
4     5     1    False

In [45]:
rolls.is_pair.mean()

0.16476

#### SOLUTION THREE

In [46]:
# Numpy Only
a = np.random.choice([1, 2, 3, 4, 5, 6], size=100000)
b = np.random.choice([1, 2, 3, 4, 5, 6], size=100000)
(a == b).mean()

0.16567

### If you flip 8 coins, what is the probability of getting exactly 3 heads? 

#### SOLUTION ONE

In [4]:
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = np.random.choice([0,1], n_trials * n_coins).reshape(nrows, ncols)
flips

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0]])

In [5]:
sums_by_trial = flips.sum(axis=1)
sums_by_trial

array([3, 5, 6, ..., 3, 6, 2])

In [6]:
exactly_3 = sums_by_trial == 3
exactly_3

array([ True, False, False, ...,  True, False, False])

In [7]:
exactly_3_rate = exactly_3.astype(int).mean()
print(f"Based on a simulation of 10,000 trials of 8 consecutive coin flips, the probability of flipping exactly three heads is {exactly_3_rate}.")

Based on a simulation of 10,000 trials of 8 consecutive coin flips, the probability of flipping exactly three heads is 0.2243.


### What is the probability of getting more than 3 heads?

### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

#### SOLUTION ONE

In [8]:
p_datasci = 0.25
n_boards = n_cols = 2
n_drives = n_rows = 10 ** 5

data = np.random.random((n_rows, n_cols))
data

array([[0.52367416, 0.30110826],
       [0.22483308, 0.89903466],
       [0.32563666, 0.01721882],
       ...,
       [0.46862724, 0.28377202],
       [0.62598687, 0.95912283],
       [0.44980969, 0.88367756]])

In [9]:
datasci_sighting = data < p_datasci
datasci_sighting

array([[False, False],
       [ True, False],
       [False,  True],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [10]:
datasci_sighting.sum(axis=1)

array([0, 1, 1, ..., 0, 0, 0])

In [11]:
(datasci_sighting.sum(axis=1) >= 2).mean()
print(f"Based on 10,000 simulated drives by two billboards, the probability of both billboards containing data science students is {(datasci_sighting.sum(axis=1) >= 2).mean()}.")

Based on 10,000 simulated drives by two billboards, the probability of both billboards containing data science students is 0.06325.


#### SOLUTION TWO

In [56]:
outcomes = np.random.choice(['Web Dev', 'Data Science'], size=(100_000,2),p=[.75,.25])
outcomes

array([['Web Dev', 'Web Dev'],
       ['Web Dev', 'Web Dev'],
       ['Web Dev', 'Web Dev'],
       ...,
       ['Data Science', 'Web Dev'],
       ['Web Dev', 'Data Science'],
       ['Data Science', 'Data Science']], dtype='<U12')

In [57]:
df = pd.DataFrame(outcomes)
df.columns = ['first_billboard','second_billboard']
df.head()

first_billboard second_billboard
0         Web Dev          Web Dev
1         Web Dev          Web Dev
2         Web Dev          Web Dev
3         Web Dev          Web Dev
4    Data Science          Web Dev

In [59]:
df['both_ds'] = (df.first_billboard == 'Data Science') & (df.second_billboard == 'Data Science')
df.head()

first_billboard second_billboard  both_ds
0         Web Dev          Web Dev    False
1         Web Dev          Web Dev    False
2         Web Dev          Web Dev    False
3         Web Dev          Web Dev    False
4    Data Science          Web Dev    False

In [60]:
df.both_ds.mean()

0.06237

### Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

#### SOLUTION ONE

In [80]:
friday_stock = []
for num in range(100000):
    stock = 17
    for n in range(5):
        stock -= np.random.uniform(low=1.5, high=4.5)
    friday_stock.append(stock)

In [81]:
in_stock = []
for stock in friday_stock:
    if stock >= 1:
        in_stock.append(1)
    else:
        in_stock.append(0)

In [82]:
chance_for_tart = sum(in_stock)/len(in_stock)
print(f"Based on a simulation of 100,000 weeks, the chance that there is at least one pop tart remaining in stock after 5 days of purchases is {chance_for_tart}.")

Based on a simulation of 100,000 weeks, the chance that there is at least one pop tart remaining in stock after 5 days of purchases is 0.69309.


#### SOLUTION TWO

In [91]:
poptarts = np.random.normal(3, 1.5, size=(100000,5))
poptarts

array([[0.88713695, 1.60400263, 3.0448922 , 2.19999518, 3.32883595],
       [4.16947469, 3.71485252, 0.1028198 , 6.6933165 , 4.55461116],
       [2.69360966, 2.55759654, 4.89528635, 4.75820461, 1.4955688 ],
       ...,
       [6.67242957, 5.28491963, 3.80237457, 1.27471279, 3.57493706],
       [3.08435568, 4.75916761, 1.06358817, 3.24141873, 2.57071955],
       [5.36682103, 2.60149065, 1.22297659, 5.74352453, 1.38997594]])

In [92]:
poptarts = np.round(np.random.normal(3, 1.5, size=(100000,5)))
poptarts[0]

array([1., 2., 1., 2., 1.])

In [93]:
weekly_demand = poptarts.sum(axis=1)

In [94]:
(weekly_demand <17).mean()

0.66837

### Compare Heights

#### Men have an average height of 178 cm and standard deviation of 8cm.
#### Women have a mean of 170, sd = 6cm.
#### If a man and woman are chosen at random, P(woman taller than man)?

In [15]:
man_height = np.random.normal(178, 8, size=(10000,1)).tolist()
woman_height = np.random.normal(170,6, size=(10000,1)).tolist()

In [16]:
woman_taller = []
for i in range(len(man_height)):
    if woman_height[i][0] > man_height[i][0]:
        woman_taller.append(1)
    else:
        woman_taller.append(0)

In [17]:
chance_woman_taller = sum(woman_taller)/len(woman_taller)
print(f"After simulating 10,000 comparisons of a random woman to a random man, the probability that any given woman is taller than any given man is {chance_woman_taller}.")

After simulating 10,000 comparisons of a random woman to a random man, the probability that any given woman is taller than any given man is 0.2126.


#### SOLUTION TWO

In [97]:
trials = 100000
man_height = np.random.normal(178, 8, trials)
woman_height = np.random.normal(170,6, trials)

In [98]:
(woman_height > man_height)

array([False,  True, False, ...,  True,  True,  True])

In [100]:
(woman_height > man_height).mean()

0.21256

### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

#### SOLUTION ONE

In [18]:
n_trials = 10000
n_students = 50
p_fail = 1/250

installs = np.random.random((n_trials,n_students))

In [19]:
install_failure = installs < p_fail
install_failure

array([[False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [20]:
(install_failure.sum(axis=1) >= 1)

array([ True, False, False, ...,  True, False,  True])

In [21]:
print(f"After running 10,000 simulations, the probability that there are no failures in a group of 50 students: {1-(install_failure.sum(axis=1)>=1).mean()}")

After running 10,000 simulations, the probability that there are no failures in a group of 50 students: 0.8148


#### SOLUTION TWO

In [103]:
trials = 100_000
students_per_trial = 50
# 0 is fail, 1 is success
installs = np.random.choice([0,1], size = (trials, students_per_trial),p=[1/250,249/250])
df = pd.DataFrame(installs)
df.head()

0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
1   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
2   1   1   1   0   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
3   1   1   1   1   0   1   1   1   1   1  ...   1   1   1   1   1   1   1   
4   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   

   47  48  49  
0   1   1   1  
1   1   1   1  
2   1   1   1  
3   1   1   1  
4   1   1   1  

[5 rows x 50 columns]

In [105]:
# If the sum of all the successess (1) equals the number of students in the trial, then the trial was 100% success
df['all_good'] = df.sum(axis=1) == students_per_trial
df.head()

0  1  2  3  4  5  6  7  8  9  ...  41  42  43  44  45  46  47  48  49  \
0  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
1  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
2  1  1  1  0  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
3  1  1  1  1  0  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   
4  1  1  1  1  1  1  1  1  1  1  ...   1   1   1   1   1   1   1   1   1   

   all_good  
0      True  
1      True  
2     False  
3     False  
4      True  

[5 rows x 51 columns]

In [106]:
df.all_good.mean()

0.8182

### 100 students?

In [107]:
n_students = 100
installs = np.random.random((n_trials,n_students))
install_failure = installs < p_fail
print(f"After running 10,000 simulations, the probability that there are no failures in a group of 100 students: {1-(install_failure.sum(axis=1)>=1).mean()}")

After running 10,000 simulations, the probability that there are no failures in a group of 100 students: 0.6680200000000001


### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [110]:
n_students = 150
installs = np.random.random((n_trials,n_students))
install_failure = installs < p_fail
print(f"After running 10,000 simulations, the probability that there are no failures in a group of 150 students: {(install_failure.sum(axis=1)>=1).mean()}")

After running 10,000 simulations, the probability that there are no failures in a group of 150 students: 0.45015


In [109]:
(249/250)**150

0.5481516977496729

### How likely is it that 450 students all download anaconda without an issue?

In [24]:
n_students = 450
installs = np.random.random((n_trials,n_students))
install_failure = installs < p_fail
print(f"After running 10,000 simulations, the probability that there are no failures in a group of 450 students: {1-(install_failure.sum(axis=1)>=1).mean()}")

After running 10,000 simulations, the probability that there are no failures in a group of 450 students: 0.16879999999999995


### There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [25]:
p_food = .70
n_trials = 10000
n_days = 3

food_truck = np.random.random((n_trials, n_days))
food_truck

array([[0.85769224, 0.80032733, 0.71057881],
       [0.49072275, 0.20748525, 0.43164126],
       [0.9754546 , 0.48757196, 0.68411212],
       ...,
       [0.72868148, 0.43491399, 0.25175779],
       [0.95673347, 0.83199687, 0.67132019],
       [0.97338735, 0.03091319, 0.48831878]])

In [26]:
food_truck_present = food_truck < p_food
food_truck_present

array([[False, False, False],
       [ True,  True,  True],
       [False,  True,  True],
       ...,
       [False,  True,  True],
       [False, False,  True],
       [False,  True,  True]])

In [27]:
(food_truck_present.sum(axis=1) == 0)

array([ True, False, False, ..., False, False, False])

In [28]:
no_food_3_days = (food_truck_present.sum(axis=1) == 0).mean()
no_food_3_days

0.0278

In [29]:
print(f"After 10,000 simulations, the probability that there would be no food truck for all 3 days: {no_food_3_days}")

After 10,000 simulations, the probability that there would be no food truck for all 3 days: 0.0278


#### SOLUTION TWO

In [113]:
#1 is a truck, 0 is no truck
trucks = np.random.choice([1,0], size=(100000,3),p=[.7,.3])
df = pd.DataFrame(trucks)
df.columns = ['day_1', 'day_2', 'day_3']
df.head()

day_1  day_2  day_3
0      1      0      1
1      1      0      1
2      1      1      1
3      0      1      0
4      1      1      0

In [114]:
#Theoretical probablity of seeing no food trucks across all 3 days
.3 ** 3

0.026999999999999996

In [115]:
df['appearances'] = df.sum(axis=1)
df.head()

day_1  day_2  day_3  appearances
0      1      0      1            2
1      1      0      1            2
2      1      1      1            3
3      0      1      0            1
4      1      1      0            2

In [116]:
(df.appearances == 0).mean()

0.02776

### How likely is it that a food truck will show up sometime this week?

In [30]:
p_food = .70
n_trials = 10000
n_days = 7

food_truck = np.random.random((n_trials, n_days))
food_truck

array([[0.82362966, 0.48518064, 0.59832284, ..., 0.36197704, 0.35796501,
        0.21457426],
       [0.67455267, 0.32256746, 0.93606459, ..., 0.2946364 , 0.48016794,
        0.92708789],
       [0.84056316, 0.21086955, 0.17370007, ..., 0.81261892, 0.52686485,
        0.01686217],
       ...,
       [0.94971857, 0.44650045, 0.80551779, ..., 0.76847661, 0.10800821,
        0.42607581],
       [0.65066617, 0.76981336, 0.06679755, ..., 0.95101963, 0.94136017,
        0.69983771],
       [0.56952336, 0.18027006, 0.82738404, ..., 0.54219219, 0.03063603,
        0.83949336]])

In [31]:
food_truck_present = food_truck < p_food
food_truck_present

array([[False,  True,  True, ...,  True,  True,  True],
       [ True,  True, False, ...,  True,  True, False],
       [False,  True,  True, ..., False,  True,  True],
       ...,
       [False,  True, False, ..., False,  True,  True],
       [ True, False,  True, ..., False, False,  True],
       [ True,  True, False, ...,  True,  True, False]])

In [32]:
(food_truck_present.sum(axis=1) >= 1)

array([ True,  True,  True, ...,  True,  True,  True])

In [33]:
at_least_1_food_7_days = (food_truck_present.sum(axis=1) >= 1).mean()
at_least_1_food_7_days

0.9998

In [34]:
print(f"The probability that there will be at least one food truck present at some point during any given week: {at_least_1_food_7_days}")

The probability that there will be at least one food truck present at some point during any given week: 0.9998


### If 23 people are in the same room, what are the odds that two of them share a birthday?

In [35]:
birthdays = list(range(1,366))
n_trials = 10_000
n_students = 23

rooms = np.random.choice(birthdays,n_trials * n_students).reshape(n_trials, n_students)
rooms

array([[ 87, 165, 326, ..., 133, 256, 316],
       [ 63, 110, 176, ..., 304,   2,  80],
       [222, 232,  97, ..., 355, 152, 117],
       ...,
       [334, 115, 357, ..., 253,  37, 168],
       [127, 304, 102, ..., 352,  74, 130],
       [223, 291, 127, ...,  19, 120, 142]])

In [36]:
matches = []
for room in rooms:
    if len(set(room)) != len(room):
        matches.append(1)
    else:
        matches.append(0)
        
percent_matches = sum(matches)/len(matches)
print(f"Based on 10,000 simulations, in a room of 23 people, assuming perfectly equal distribution among birthdays, the probability that there is at least one shared birthday: {percent_matches}")

Based on 10,000 simulations, in a room of 23 people, assuming perfectly equal distribution among birthdays, the probability that there is at least one shared birthday: 0.5055


#### SOLUTION TWO

In [117]:
n_simulations = 100_000
n_people = 23

birthdays = np.random.choice(range(365), size=(n_simulations, n_people))
df = pd.DataFrame(birthdays)
df.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0   89  119   48  342  357  237   83  202    1  294  ...  186  175  185  201   
1  117  212   44  233  191   87  135  256  105  111  ...   32  252  129  223   
2  255  105  159  171  207  311  191  278  231  296  ...  238  178  141  211   
3   48  287   81  235  316  107   65  208    9  260  ...  191    2  268  319   
4  141  341   69  176  263  101  333  255  148  340  ...  185   90   24  226   

    17   18   19   20   21   22  
0   28  111  136   55  212  150  
1  339  218  361  350  210  252  
2  363  297   15   66  211   63  
3  229  120  358  320    9  282  
4  118  170  305  259  266  286  

[5 rows x 23 columns]

In [118]:
# get the number of unique values per row (per observation)
# if the number of unique values == number of people in the room,
# then everyone has a different birthday
df['n_unique'] = df.nunique(axis=1)
df.head()

0    1    2    3    4    5    6    7    8    9  ...   14   15   16   17  \
0   89  119   48  342  357  237   83  202    1  294  ...  175  185  201   28   
1  117  212   44  233  191   87  135  256  105  111  ...  252  129  223  339   
2  255  105  159  171  207  311  191  278  231  296  ...  178  141  211  363   
3   48  287   81  235  316  107   65  208    9  260  ...    2  268  319  229   
4  141  341   69  176  263  101  333  255  148  340  ...   90   24  226  118   

    18   19   20   21   22  n_unique  
0  111  136   55  212  150        23  
1  218  361  350  210  252        21  
2  297   15   66  211   63        22  
3  120  358  320    9  282        22  
4  170  305  259  266  286        22  

[5 rows x 24 columns]

In [120]:
(df.n_unique != 23).mean()

0.5095

### What if it's 20 people? 

In [37]:
birthdays = list(range(1,366))
n_trials = 10_000
n_students = 20

rooms = np.random.choice(birthdays,n_trials * n_students).reshape(n_trials, n_students)
rooms

array([[306, 195,  73, ..., 121,  97,  51],
       [ 42,  59, 210, ..., 167,  41, 157],
       [ 53, 117, 119, ..., 233, 231, 294],
       ...,
       [  5, 246, 350, ...,  45, 185, 275],
       [349, 310, 339, ..., 233,  29, 252],
       [354, 303, 289, ...,  62,  82, 316]])

In [38]:
matches = []
for room in rooms:
    if len(set(room)) != len(room):
        matches.append(1)
    else:
        matches.append(0)
        
percent_matches = sum(matches)/len(matches)
print(f"Based on 10,000 simulations, in a room of 20 people, assuming perfectly equal distribution among birthdays, the probability that there is at least one shared birthday: {percent_matches}")

Based on 10,000 simulations, in a room of 20 people, assuming perfectly equal distribution among birthdays, the probability that there is at least one shared birthday: 0.411


#### SOLUTION TWO

In [122]:
n_simulations = 100_000
n_people = 20

birthdays = np.random.choice(range(365), size=(n_simulations, n_people))
df = pd.DataFrame(birthdays)
df['n_unique'] = df.nunique(axis=1)
(df.n_unique != 20).mean()

0.40948

### 40?

In [39]:
birthdays = list(range(1,366))
n_trials = 10_000
n_students = 40

rooms = np.random.choice(birthdays,n_trials * n_students).reshape(n_trials, n_students)
rooms

array([[ 66, 107,  97, ..., 324, 115,  53],
       [144,  10, 148, ..., 100, 186,  81],
       [136,  15, 246, ..., 124, 178, 224],
       ...,
       [167, 267,  29, ..., 169, 186, 181],
       [351, 294, 228, ..., 281, 152, 106],
       [120,  59, 123, ..., 131, 257, 116]])

In [40]:
matches = []
for room in rooms:
    if len(set(room)) != len(room):
        matches.append(1)
    else:
        matches.append(0)
        
percent_matches = sum(matches)/len(matches)
print(f"Based on 10,000 simulations, in a room of 40 people, assuming perfectly equal distribution among birthdays, the probability that there is at least one shared birthday: {percent_matches}")

Based on 10,000 simulations, in a room of 40 people, assuming perfectly equal distribution among birthdays, the probability that there is at least one shared birthday: 0.89


#### SOLUTION TWO

In [123]:
n_simulations = 100_000
n_people = 40

birthdays = np.random.choice(range(365), size=(n_simulations, n_people))
df = pd.DataFrame(birthdays)
df['n_unique'] = df.nunique(axis=1)
(df.n_unique != 40).mean()

0.8926